@baseUrl = http://127.0.0.1:3000

# Messages
### List all messages
GET {{baseUrl}}/messages
?limit=10
&page=0
&orderBy=id
&orderDirection=asc
Authorization: Bearer 123456

### Get a message
GET {{baseUrl}}/messages/6
Authorization: Bearer 123456

### Create a message
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "texto": "De Letícia para Lucas",
  "deId": 25,
  "paraId": 26
}

### Update a message
PATCH {{baseUrl}}/messages/6
Content-Type: application/json

{
  "texto": "Teste recado",
  "lido": true
}

### Delete a message
DELETE {{baseUrl}}/messages/1


# People
### List all people
GET {{baseUrl}}/person/
?limit=10
&offset=0

### List a person
GET {{baseUrl}}/person/26/

### Create a person
POST {{baseUrl}}/person/
Content-Type: application/json

{
    "email": "lucas@email.com",
    "password": "123456",
    "nome": "Lucas"
}

### Update a person
PATCH {{baseUrl}}/person/23
Content-Type: application/json

{
    "password": "123456",
    "nome": "Lucas Updated"
}

### Remove a person
DELETE {{baseUrl}}/person/24