@baseUrl = http://127.0.0.1:3000

# Messages
### List all messages
GET {{baseUrl}}/messages
?limit=20
&offset=30

### Get a message
GET {{baseUrl}}/messages/2

### Create a message
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "texto": "Novo recado",
  "de": "Lucas",
  "para": "Letícia"
}

### Update a message
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
  "texto": "Updated recado",
  "lido": false
}

### Delete a message
DELETE {{baseUrl}}/messages/1


# People
### List all people
GET {{baseUrl}}/person/
?limit=10
&offset=0

### List a person
GET {{baseUrl}}/person/1/

### Create a person
POST {{baseUrl}}/person/
Content-Type: application/json

{
    "email": "lucas@email.com",
    "password": "123456",
    "nome": "Lucas"
}

### Update a person
PATCH {{baseUrl}}/person/23
Content-Type: application/json

{
    "password": "123456",
    "nome": "Lucas Updated"
}

### Remove a person
DELETE {{{baseUrl}}}/person/1